import { useEffect } from "react";

/**
 * Registers the service worker generated by vite-plugin-pwa.
 * Guarded against iframes / preview hosts and SSR.
 */
export function PWARegister() {
  useEffect(() => {
    if (typeof window === "undefined") return;
    if (window.self !== window.top) return;
    const host = window.location.hostname;
    if (host.includes("lovable.app") || host.includes("lovable.dev")) return;
    if (!("serviceWorker" in navigator)) return;

    // Dynamic import via variable to avoid TS resolution of virtual module at build time.
    const mod = "virtual:pwa-register";
    (import(/* @vite-ignore */ mod) as Promise<{ registerSW: (o?: any) => any }>)
      .then(({ registerSW }) => registerSW({ immediate: true }))
      .catch(() => {});
  }, []);
  return null;
}
