/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as OfficeIndexRouteImport } from './routes/office.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RiderWaybillRouteImport } from './routes/rider.waybill'
import { Route as RiderScanRouteImport } from './routes/rider.scan'
import { Route as RiderProfileRouteImport } from './routes/rider.profile'
import { Route as RiderPickupsRouteImport } from './routes/rider.pickups'
import { Route as RiderListRouteImport } from './routes/rider.list'
import { Route as OfficeWaybillRouteImport } from './routes/office.waybill'
import { Route as OfficePendingRouteImport } from './routes/office.pending'
import { Route as OfficeMenuRouteImport } from './routes/office.menu'
import { Route as OfficeExternalRouteImport } from './routes/office.external'
import { Route as OfficeDispatchRouteImport } from './routes/office.dispatch'
import { Route as OfficeCodRouteImport } from './routes/office.cod'
import { Route as OfficeBagsRouteImport } from './routes/office.bags'
import { Route as AdminWaybillRouteImport } from './routes/admin.waybill'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPendingRouteImport } from './routes/admin.pending'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminExternalRouteImport } from './routes/admin.external'
import { Route as AdminDispatchRouteImport } from './routes/admin.dispatch'
import { Route as AdminBagsRouteImport } from './routes/admin.bags'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAlimallRouteImport } from './routes/admin.alimall'
import { Route as OfficeParcelsIndexRouteImport } from './routes/office.parcels.index'
import { Route as OfficeBagsIndexRouteImport } from './routes/office.bags.index'
import { Route as AdminParcelsIndexRouteImport } from './routes/admin.parcels.index'
import { Route as RiderParcelsIdRouteImport } from './routes/rider.parcels.$id'
import { Route as OfficeScanTypeRouteImport } from './routes/office.scan.$type'
import { Route as OfficeParcelsIdRouteImport } from './routes/office.parcels.$id'
import { Route as OfficeBagsIdRouteImport } from './routes/office.bags.$id'
import { Route as AdminScanTypeRouteImport } from './routes/admin.scan.$type'
import { Route as AdminParcelsIdRouteImport } from './routes/admin.parcels.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/rider/',
  path: '/rider/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/office/',
  path: '/office/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderWaybillRoute = RiderWaybillRouteImport.update({
  id: '/rider/waybill',
  path: '/rider/waybill',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderScanRoute = RiderScanRouteImport.update({
  id: '/rider/scan',
  path: '/rider/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/rider/profile',
  path: '/rider/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderPickupsRoute = RiderPickupsRouteImport.update({
  id: '/rider/pickups',
  path: '/rider/pickups',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderListRoute = RiderListRouteImport.update({
  id: '/rider/list',
  path: '/rider/list',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeWaybillRoute = OfficeWaybillRouteImport.update({
  id: '/office/waybill',
  path: '/office/waybill',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficePendingRoute = OfficePendingRouteImport.update({
  id: '/office/pending',
  path: '/office/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeMenuRoute = OfficeMenuRouteImport.update({
  id: '/office/menu',
  path: '/office/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeExternalRoute = OfficeExternalRouteImport.update({
  id: '/office/external',
  path: '/office/external',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeDispatchRoute = OfficeDispatchRouteImport.update({
  id: '/office/dispatch',
  path: '/office/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeCodRoute = OfficeCodRouteImport.update({
  id: '/office/cod',
  path: '/office/cod',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeBagsRoute = OfficeBagsRouteImport.update({
  id: '/office/bags',
  path: '/office/bags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaybillRoute = AdminWaybillRouteImport.update({
  id: '/admin/waybill',
  path: '/admin/waybill',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/admin/sites',
  path: '/admin/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/admin/pending',
  path: '/admin/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExternalRoute = AdminExternalRouteImport.update({
  id: '/admin/external',
  path: '/admin/external',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDispatchRoute = AdminDispatchRouteImport.update({
  id: '/admin/dispatch',
  path: '/admin/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBagsRoute = AdminBagsRouteImport.update({
  id: '/admin/bags',
  path: '/admin/bags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlimallRoute = AdminAlimallRouteImport.update({
  id: '/admin/alimall',
  path: '/admin/alimall',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeParcelsIndexRoute = OfficeParcelsIndexRouteImport.update({
  id: '/office/parcels/',
  path: '/office/parcels/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeBagsIndexRoute = OfficeBagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeBagsRoute,
} as any)
const AdminParcelsIndexRoute = AdminParcelsIndexRouteImport.update({
  id: '/admin/parcels/',
  path: '/admin/parcels/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderParcelsIdRoute = RiderParcelsIdRouteImport.update({
  id: '/rider/parcels/$id',
  path: '/rider/parcels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeScanTypeRoute = OfficeScanTypeRouteImport.update({
  id: '/office/scan/$type',
  path: '/office/scan/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeParcelsIdRoute = OfficeParcelsIdRouteImport.update({
  id: '/office/parcels/$id',
  path: '/office/parcels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeBagsIdRoute = OfficeBagsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OfficeBagsRoute,
} as any)
const AdminScanTypeRoute = AdminScanTypeRouteImport.update({
  id: '/admin/scan/$type',
  path: '/admin/scan/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParcelsIdRoute = AdminParcelsIdRouteImport.update({
  id: '/admin/parcels/$id',
  path: '/admin/parcels/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/admin/alimall': typeof AdminAlimallRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bags': typeof AdminBagsRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/external': typeof AdminExternalRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waybill': typeof AdminWaybillRoute
  '/office/bags': typeof OfficeBagsRouteWithChildren
  '/office/cod': typeof OfficeCodRoute
  '/office/dispatch': typeof OfficeDispatchRoute
  '/office/external': typeof OfficeExternalRoute
  '/office/menu': typeof OfficeMenuRoute
  '/office/pending': typeof OfficePendingRoute
  '/office/waybill': typeof OfficeWaybillRoute
  '/rider/list': typeof RiderListRoute
  '/rider/pickups': typeof RiderPickupsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/scan': typeof RiderScanRoute
  '/rider/waybill': typeof RiderWaybillRoute
  '/admin/': typeof AdminIndexRoute
  '/office/': typeof OfficeIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/admin/parcels/$id': typeof AdminParcelsIdRoute
  '/admin/scan/$type': typeof AdminScanTypeRoute
  '/office/bags/$id': typeof OfficeBagsIdRoute
  '/office/parcels/$id': typeof OfficeParcelsIdRoute
  '/office/scan/$type': typeof OfficeScanTypeRoute
  '/rider/parcels/$id': typeof RiderParcelsIdRoute
  '/admin/parcels/': typeof AdminParcelsIndexRoute
  '/office/bags/': typeof OfficeBagsIndexRoute
  '/office/parcels/': typeof OfficeParcelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/admin/alimall': typeof AdminAlimallRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bags': typeof AdminBagsRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/external': typeof AdminExternalRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waybill': typeof AdminWaybillRoute
  '/office/cod': typeof OfficeCodRoute
  '/office/dispatch': typeof OfficeDispatchRoute
  '/office/external': typeof OfficeExternalRoute
  '/office/menu': typeof OfficeMenuRoute
  '/office/pending': typeof OfficePendingRoute
  '/office/waybill': typeof OfficeWaybillRoute
  '/rider/list': typeof RiderListRoute
  '/rider/pickups': typeof RiderPickupsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/scan': typeof RiderScanRoute
  '/rider/waybill': typeof RiderWaybillRoute
  '/admin': typeof AdminIndexRoute
  '/office': typeof OfficeIndexRoute
  '/rider': typeof RiderIndexRoute
  '/admin/parcels/$id': typeof AdminParcelsIdRoute
  '/admin/scan/$type': typeof AdminScanTypeRoute
  '/office/bags/$id': typeof OfficeBagsIdRoute
  '/office/parcels/$id': typeof OfficeParcelsIdRoute
  '/office/scan/$type': typeof OfficeScanTypeRoute
  '/rider/parcels/$id': typeof RiderParcelsIdRoute
  '/admin/parcels': typeof AdminParcelsIndexRoute
  '/office/bags': typeof OfficeBagsIndexRoute
  '/office/parcels': typeof OfficeParcelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/admin/alimall': typeof AdminAlimallRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bags': typeof AdminBagsRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/external': typeof AdminExternalRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waybill': typeof AdminWaybillRoute
  '/office/bags': typeof OfficeBagsRouteWithChildren
  '/office/cod': typeof OfficeCodRoute
  '/office/dispatch': typeof OfficeDispatchRoute
  '/office/external': typeof OfficeExternalRoute
  '/office/menu': typeof OfficeMenuRoute
  '/office/pending': typeof OfficePendingRoute
  '/office/waybill': typeof OfficeWaybillRoute
  '/rider/list': typeof RiderListRoute
  '/rider/pickups': typeof RiderPickupsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/scan': typeof RiderScanRoute
  '/rider/waybill': typeof RiderWaybillRoute
  '/admin/': typeof AdminIndexRoute
  '/office/': typeof OfficeIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/admin/parcels/$id': typeof AdminParcelsIdRoute
  '/admin/scan/$type': typeof AdminScanTypeRoute
  '/office/bags/$id': typeof OfficeBagsIdRoute
  '/office/parcels/$id': typeof OfficeParcelsIdRoute
  '/office/scan/$type': typeof OfficeScanTypeRoute
  '/rider/parcels/$id': typeof RiderParcelsIdRoute
  '/admin/parcels/': typeof AdminParcelsIndexRoute
  '/office/bags/': typeof OfficeBagsIndexRoute
  '/office/parcels/': typeof OfficeParcelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/reset-password'
    | '/track'
    | '/admin/alimall'
    | '/admin/audit'
    | '/admin/bags'
    | '/admin/dispatch'
    | '/admin/external'
    | '/admin/menu'
    | '/admin/pending'
    | '/admin/reports'
    | '/admin/sites'
    | '/admin/users'
    | '/admin/waybill'
    | '/office/bags'
    | '/office/cod'
    | '/office/dispatch'
    | '/office/external'
    | '/office/menu'
    | '/office/pending'
    | '/office/waybill'
    | '/rider/list'
    | '/rider/pickups'
    | '/rider/profile'
    | '/rider/scan'
    | '/rider/waybill'
    | '/admin/'
    | '/office/'
    | '/rider/'
    | '/admin/parcels/$id'
    | '/admin/scan/$type'
    | '/office/bags/$id'
    | '/office/parcels/$id'
    | '/office/scan/$type'
    | '/rider/parcels/$id'
    | '/admin/parcels/'
    | '/office/bags/'
    | '/office/parcels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/reset-password'
    | '/track'
    | '/admin/alimall'
    | '/admin/audit'
    | '/admin/bags'
    | '/admin/dispatch'
    | '/admin/external'
    | '/admin/menu'
    | '/admin/pending'
    | '/admin/reports'
    | '/admin/sites'
    | '/admin/users'
    | '/admin/waybill'
    | '/office/cod'
    | '/office/dispatch'
    | '/office/external'
    | '/office/menu'
    | '/office/pending'
    | '/office/waybill'
    | '/rider/list'
    | '/rider/pickups'
    | '/rider/profile'
    | '/rider/scan'
    | '/rider/waybill'
    | '/admin'
    | '/office'
    | '/rider'
    | '/admin/parcels/$id'
    | '/admin/scan/$type'
    | '/office/bags/$id'
    | '/office/parcels/$id'
    | '/office/scan/$type'
    | '/rider/parcels/$id'
    | '/admin/parcels'
    | '/office/bags'
    | '/office/parcels'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/reset-password'
    | '/track'
    | '/admin/alimall'
    | '/admin/audit'
    | '/admin/bags'
    | '/admin/dispatch'
    | '/admin/external'
    | '/admin/menu'
    | '/admin/pending'
    | '/admin/reports'
    | '/admin/sites'
    | '/admin/users'
    | '/admin/waybill'
    | '/office/bags'
    | '/office/cod'
    | '/office/dispatch'
    | '/office/external'
    | '/office/menu'
    | '/office/pending'
    | '/office/waybill'
    | '/rider/list'
    | '/rider/pickups'
    | '/rider/profile'
    | '/rider/scan'
    | '/rider/waybill'
    | '/admin/'
    | '/office/'
    | '/rider/'
    | '/admin/parcels/$id'
    | '/admin/scan/$type'
    | '/office/bags/$id'
    | '/office/parcels/$id'
    | '/office/scan/$type'
    | '/rider/parcels/$id'
    | '/admin/parcels/'
    | '/office/bags/'
    | '/office/parcels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrackRoute: typeof TrackRoute
  AdminAlimallRoute: typeof AdminAlimallRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBagsRoute: typeof AdminBagsRoute
  AdminDispatchRoute: typeof AdminDispatchRoute
  AdminExternalRoute: typeof AdminExternalRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWaybillRoute: typeof AdminWaybillRoute
  OfficeBagsRoute: typeof OfficeBagsRouteWithChildren
  OfficeCodRoute: typeof OfficeCodRoute
  OfficeDispatchRoute: typeof OfficeDispatchRoute
  OfficeExternalRoute: typeof OfficeExternalRoute
  OfficeMenuRoute: typeof OfficeMenuRoute
  OfficePendingRoute: typeof OfficePendingRoute
  OfficeWaybillRoute: typeof OfficeWaybillRoute
  RiderListRoute: typeof RiderListRoute
  RiderPickupsRoute: typeof RiderPickupsRoute
  RiderProfileRoute: typeof RiderProfileRoute
  RiderScanRoute: typeof RiderScanRoute
  RiderWaybillRoute: typeof RiderWaybillRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
  RiderIndexRoute: typeof RiderIndexRoute
  AdminParcelsIdRoute: typeof AdminParcelsIdRoute
  AdminScanTypeRoute: typeof AdminScanTypeRoute
  OfficeParcelsIdRoute: typeof OfficeParcelsIdRoute
  OfficeScanTypeRoute: typeof OfficeScanTypeRoute
  RiderParcelsIdRoute: typeof RiderParcelsIdRoute
  AdminParcelsIndexRoute: typeof AdminParcelsIndexRoute
  OfficeParcelsIndexRoute: typeof OfficeParcelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/rider'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/office'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/waybill': {
      id: '/rider/waybill'
      path: '/rider/waybill'
      fullPath: '/rider/waybill'
      preLoaderRoute: typeof RiderWaybillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/scan': {
      id: '/rider/scan'
      path: '/rider/scan'
      fullPath: '/rider/scan'
      preLoaderRoute: typeof RiderScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/rider/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/pickups': {
      id: '/rider/pickups'
      path: '/rider/pickups'
      fullPath: '/rider/pickups'
      preLoaderRoute: typeof RiderPickupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/list': {
      id: '/rider/list'
      path: '/rider/list'
      fullPath: '/rider/list'
      preLoaderRoute: typeof RiderListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/waybill': {
      id: '/office/waybill'
      path: '/office/waybill'
      fullPath: '/office/waybill'
      preLoaderRoute: typeof OfficeWaybillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/pending': {
      id: '/office/pending'
      path: '/office/pending'
      fullPath: '/office/pending'
      preLoaderRoute: typeof OfficePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/menu': {
      id: '/office/menu'
      path: '/office/menu'
      fullPath: '/office/menu'
      preLoaderRoute: typeof OfficeMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/external': {
      id: '/office/external'
      path: '/office/external'
      fullPath: '/office/external'
      preLoaderRoute: typeof OfficeExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/dispatch': {
      id: '/office/dispatch'
      path: '/office/dispatch'
      fullPath: '/office/dispatch'
      preLoaderRoute: typeof OfficeDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/cod': {
      id: '/office/cod'
      path: '/office/cod'
      fullPath: '/office/cod'
      preLoaderRoute: typeof OfficeCodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/bags': {
      id: '/office/bags'
      path: '/office/bags'
      fullPath: '/office/bags'
      preLoaderRoute: typeof OfficeBagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waybill': {
      id: '/admin/waybill'
      path: '/admin/waybill'
      fullPath: '/admin/waybill'
      preLoaderRoute: typeof AdminWaybillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/admin/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/admin/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/external': {
      id: '/admin/external'
      path: '/admin/external'
      fullPath: '/admin/external'
      preLoaderRoute: typeof AdminExternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dispatch': {
      id: '/admin/dispatch'
      path: '/admin/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AdminDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bags': {
      id: '/admin/bags'
      path: '/admin/bags'
      fullPath: '/admin/bags'
      preLoaderRoute: typeof AdminBagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alimall': {
      id: '/admin/alimall'
      path: '/admin/alimall'
      fullPath: '/admin/alimall'
      preLoaderRoute: typeof AdminAlimallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/parcels/': {
      id: '/office/parcels/'
      path: '/office/parcels'
      fullPath: '/office/parcels/'
      preLoaderRoute: typeof OfficeParcelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/bags/': {
      id: '/office/bags/'
      path: '/'
      fullPath: '/office/bags/'
      preLoaderRoute: typeof OfficeBagsIndexRouteImport
      parentRoute: typeof OfficeBagsRoute
    }
    '/admin/parcels/': {
      id: '/admin/parcels/'
      path: '/admin/parcels'
      fullPath: '/admin/parcels/'
      preLoaderRoute: typeof AdminParcelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/parcels/$id': {
      id: '/rider/parcels/$id'
      path: '/rider/parcels/$id'
      fullPath: '/rider/parcels/$id'
      preLoaderRoute: typeof RiderParcelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/scan/$type': {
      id: '/office/scan/$type'
      path: '/office/scan/$type'
      fullPath: '/office/scan/$type'
      preLoaderRoute: typeof OfficeScanTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/parcels/$id': {
      id: '/office/parcels/$id'
      path: '/office/parcels/$id'
      fullPath: '/office/parcels/$id'
      preLoaderRoute: typeof OfficeParcelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/bags/$id': {
      id: '/office/bags/$id'
      path: '/$id'
      fullPath: '/office/bags/$id'
      preLoaderRoute: typeof OfficeBagsIdRouteImport
      parentRoute: typeof OfficeBagsRoute
    }
    '/admin/scan/$type': {
      id: '/admin/scan/$type'
      path: '/admin/scan/$type'
      fullPath: '/admin/scan/$type'
      preLoaderRoute: typeof AdminScanTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parcels/$id': {
      id: '/admin/parcels/$id'
      path: '/admin/parcels/$id'
      fullPath: '/admin/parcels/$id'
      preLoaderRoute: typeof AdminParcelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OfficeBagsRouteChildren {
  OfficeBagsIdRoute: typeof OfficeBagsIdRoute
  OfficeBagsIndexRoute: typeof OfficeBagsIndexRoute
}

const OfficeBagsRouteChildren: OfficeBagsRouteChildren = {
  OfficeBagsIdRoute: OfficeBagsIdRoute,
  OfficeBagsIndexRoute: OfficeBagsIndexRoute,
}

const OfficeBagsRouteWithChildren = OfficeBagsRoute._addFileChildren(
  OfficeBagsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrackRoute: TrackRoute,
  AdminAlimallRoute: AdminAlimallRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBagsRoute: AdminBagsRoute,
  AdminDispatchRoute: AdminDispatchRoute,
  AdminExternalRoute: AdminExternalRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWaybillRoute: AdminWaybillRoute,
  OfficeBagsRoute: OfficeBagsRouteWithChildren,
  OfficeCodRoute: OfficeCodRoute,
  OfficeDispatchRoute: OfficeDispatchRoute,
  OfficeExternalRoute: OfficeExternalRoute,
  OfficeMenuRoute: OfficeMenuRoute,
  OfficePendingRoute: OfficePendingRoute,
  OfficeWaybillRoute: OfficeWaybillRoute,
  RiderListRoute: RiderListRoute,
  RiderPickupsRoute: RiderPickupsRoute,
  RiderProfileRoute: RiderProfileRoute,
  RiderScanRoute: RiderScanRoute,
  RiderWaybillRoute: RiderWaybillRoute,
  AdminIndexRoute: AdminIndexRoute,
  OfficeIndexRoute: OfficeIndexRoute,
  RiderIndexRoute: RiderIndexRoute,
  AdminParcelsIdRoute: AdminParcelsIdRoute,
  AdminScanTypeRoute: AdminScanTypeRoute,
  OfficeParcelsIdRoute: OfficeParcelsIdRoute,
  OfficeScanTypeRoute: OfficeScanTypeRoute,
  RiderParcelsIdRoute: RiderParcelsIdRoute,
  AdminParcelsIndexRoute: AdminParcelsIndexRoute,
  OfficeParcelsIndexRoute: OfficeParcelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
